language: java

jdk:
    - openjdk12

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

addons:
  sonarcloud:
    organization: "richardeigenmann-github" # the key of the org you chose at step #3
    token:
      secure: jRO0awuasmxRuKkUxK0G6Dn8jLpt3Rdi6Q8+HsjkEb7MClB6+6U+wm++NJCu1BWphzFzJLarLjxw8wtH+fpkhx+CGALiHOh3bMtV4o4rNNHC98w1nsmBckkiSMQaekXUJMUkFVvY2P4bWJshyQO0zIDBXIG93tU4PjClPWzx9mAWkjEU79lBHVd9uPCtyr4ocWiH4rngP20WhuXZHE0nqnCL7HOB/TD+n5ynfbvHOcUZ5KzO4eN5B5kCqDPqyg1eNnDLW7SIBo+hej0LPro7LbCKzsg3BjT2E48JibM9xIjVaQhGCBrnJ8Z63+3GAfHP87k4LUDt3D7MwnTxRzwjiIKk6+YBHQII/k5fSBLLYh+tgrr6arwUmHK+efREBQkFiNz7SXG3IKKnweLoe1bpIFik/eegrD3q/D+tLeP1BFwbqeifaev+g5e2UfOwomlr4R/i3BEbx2NCcf9hbbaFrztLJBhlQ4CizdDINIETibNORQmhMcwcFyjWwQT6gOnvWqF8iWgl5LWUf54DQwS8G48aDfpgm9SMO5WNhhcsNlN84jmWcSQiSnd67WbSJZc8+wfM9JzM5wfnhfMSGKl3tp5X1KkLOf991JM5SnaK0O+azdraiO/8qAHwSGshDm6K3/taUB9I2XilEYegGIHswFX9X3ESaNmOyk3BCCGF3W0=
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
