/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayWithDirectoryChooser.java
 *
 * Created on 10-Sep-2009, 00:42:20
 */

package jpotestground;

import jpo.gui.DirectoryChooser;

/**
 *
 * @author Richard Eigenmann
 */
public class PlayWithDirectoryChooser extends javax.swing.JFrame {

    DirectoryChooser dc = new DirectoryChooser("Filechooser", DirectoryChooser.DIR_MUST_BE_WRITABLE);
    /** Creates new form PlayWithDirectoryChooser */
    public PlayWithDirectoryChooser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

     
        getContentPane().add(dc);
        pack();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PlayWithDirectoryChooser().setVisible(true);
            }
        });
    }


}
