# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  gradle: circleci/gradle@4.1.0
jobs:
  build:
    docker:
      # from https://hub.docker.com/r/cimg/openjdk
      - image: cimg/openjdk:25.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      # We set max workers to 1 and disable the daemon to prevent OOM crashes in CI
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Xmx3000m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Install X11 Utilities
          command: |
            sudo apt-get update && sudo apt-get install -y xvfb x11-utils

      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests and Sonar
                # -a: auto-servernum finding
                # -s: set screen size to 1280x1024x24 to prevent GUI components being off-screen
                command: |
                  chmod +x gradlew
                  xvfb-run -a -s "-screen 0 1280x1024x24" ./gradlew test
#                   sonar \
#                    -Dsonar.projectKey=richardeigenmann-github \
#                    -Dsonar.host.url=$SONAR_HOST_URL \
#                    -Dsonar.token=$SONAR_TOKEN

      - store_test_results:
          path: build/test-results/test

#workflows:
#  main:
#    jobs:
#      - build:
#          context: SonarCloud