# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  #gradle: circleci/gradle@3.0.0
  gradle-orb: entur/gradle-orb@0.2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # from https://hub.docker.com/r/cimg/openjdk
      #- image: cimg/openjdk:19.0.2
      #- image: cimg/openjdk:20.0.1
      - image: cimg/openjdk:23.0.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
      #- run: gradle compileTestJava
      #- run: gradle check sonarqube

      - run:
          name: Analyze on SonarQube Cloud
          command: "gradle build sonarqube"

      - store_test_results:
          path: build/test-results/test

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud