app:
  collection:
    file-path: ${APP_COLLECTION_FILE_PATH:/dir/dir/your-collection.xml}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:MISSING_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:MISSING_CLIENT_SECRET}