spring.application.name=api
server.port=8001

app.cors.allowed-origins=http://localhost:4200,http://octan:8001

# Expose the info endpoint via the web
management.endpoints.web.exposure.include=info,health

# Optional: Enable the info git or build contributors
management.info.git.mode=full
management.info.build.enabled=true